### ISSUE TITLE
Error package 

### ISSUE THREAD

**Issue by lilnynho** [flexits/HotCornersWin#17]
There is a problem with 
the package error 2503 
my v22H2/19045.4842

**Comment by flexits** [comment]
Please provide extended context. What is the error message? When exactly do you encounter it?

**Comment by lilnynho** [comment]
> Please provide extended context. What is the error message? When exactly do you encounter it? 

Hi, flex


I find this when installing the program.


The installer has encountered an unexpected error while installing this package. This may indicate that there is a problem with the package. Error code 2503


 Ty

**Comment by flexits** [comment]
Hi! This seems to be a problem with Windows Installer. Unfortunately, I'm afraid to be unable to fix the issue since the Windows Installer is an additional component supplied by Microsoft, so somewhat out of my responsibility... Maybe you'll find [this thread](https://answers.microsoft.com/en-us/windows/forum/all/error-2503-and-2502-installinguninstalling/d1de28d1-732e-48a7-af91-aab40c471da8) useful.

>  visual c++
Not required in this case.
